application_api_version: v1beta1
properties:
  name:
    type: string
    x-google-marketplace:
     type: NAME
  namespace:
    type: string
    x-google-marketplace:
      type: NAMESPACE
  imageName:
    type: string
    default: gcr.io/divvycloud-public/marketplace/divvycloud:18
    x-google-marketplace:
      type: IMAGE




required:
- name
- namespace
- imageName
