properties:
  name:
    type: string
    x-google-marketplace:
     type: NAME
  namespace:
    type: string
    x-google-marketplace:
      type: NAMESPACE
  ubuntuImage:
    type: string
    default: launcher.gcr.io/google/ubuntu16_04:latest
    x-google-marketplace:
      type: IMAGE
required:
- name
- namespace
- ubuntuImage
