properties:
  name:
    type: string
    x-google-marketplace:
     type: NAME
  namespace:
    type: string
    x-google-marketplace:
      type: NAMESPACE
  imageName:
    type: string
    default: gcr.io/divvy-production/marketplace/divvycloud:latest
    x-google-marketplace:
      type: IMAGE
required:
- name
- namespace
- imageName
