apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "divvycloud.name" . }}-harvester
  labels:
    app: {{ template "divvycloud.name" . }}-harvester
    chart: {{ template "divvycloud.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}

spec:
  replicas: {{ if .Values.replicaCounts.harvester}}  {{ .Values.replicaCounts.harvester | default 2 }} {{ else }} 2 {{ end }}
  selector:
    matchLabels:
      app: {{ template "divvycloud.name" . }}-harvester
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "divvycloud.name" . }}-harvester
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.imageName }}
          imagePullPolicy: {{ .Values.pullPolicy }}
          args: ['divvycloudworker','-t','harvester','-n']
          envFrom:
            - secretRef:
                name: {{ template "divvycloud.name" . }}-secret 
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector::{{ .Values.image}}
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
