{{- $mysql_host := (printf "%s-mysql" (include "divvycloud.name" .)) -}}
{{- $redis_host := (printf "%s-redis" (include "divvycloud.name" .)) -}}
{{- $random_root_password := (printf "%s" (randAlpha 16)) -}}
{{- $random_password := (printf "%s" (randAlpha 16)) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "divvycloud.name" . }}-secret
data:

  DIVVY_MYSQL_DATABASE : {{ .Values.database.dbName | default "divvy" | b64enc }}
  DIVVY_MYSQL_HOST: {{ .Values.database.host | default $mysql_host | b64enc }}
  DIVVY_MYSQL_PORT: {{ .Values.database.port | default "3306" | b64enc }}
  DIVVY_MYSQL_USER : {{ .Values.database.user | default "divvy" | b64enc }}
  DIVVY_MYSQL_PASSWORD : {{ .Values.database.password | default $random_password | b64enc }}


  DIVVY_SECURE_MYSQL_DATABASE : {{ .Values.secureDatabase.dbName | default "divvykeys" | b64enc }}
  DIVVY_SECURE_MYSQL_HOST: {{ .Values.secureDatabase.host default $mysql_host | b64enc }}
  DIVVY_SECURE_MYSQL_PORT: {{ .Values.secureDatabase.port | default "3306" | b64enc }}
  DIVVY_SECURE_MYSQL_USER : {{ .Values.secureDatabase.user | default "divvy" | b64enc }}
  DIVVY_SECURE_MYSQL_PASSWORD : {{ .Values.secureDatabase.password | default $random_password | b64enc }}

  MYSQL_DATABASE : {{ .Values.databaseName | default "divvy" | b64enc }}
  MYSQL_USER: {{ .Values.databaseUser | default "divvy" | b64enc }}
  MYSQL_PASSWORD : {{ .Values.databasePassword | default $random_password | b64enc }}
  MYSQL_ROOT_PASSWORD: {{ .Values.databaseRootPassword | default $random_root_password | b64enc }}

  DIVVY_REDIS_HOST: {{ .Values.redis_host | default $redis_host  | b64enc }}



